dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.6"

before_install:
  - sudo apt-get install -y python3-pip python3-lxml python3-setuptools python3-cffi
  - sudo apt-get install -y libffi-dev libssl-dev swig

# command to install dependencies
install:
  - pip install pycryptodome
  - pip install chardet
  - pip install sortedcontainers
  - python3 setup.py -q install

# command to run tests
script:
  - python3 setup.py test
